### ISSUE TITLE
CSV Indicators - when pasting none-CSV text - is this a bug?

### ISSUE THREAD

**Issue by adamharaz** [soltra-adapters/adapter-csvind#2]
**Steps to reproduce:**
- Log into Edge 2.9 rc2 as an Admin
- Install soltra-csvind-v0.3.5.tgz
- Navigate to Adapters
- Select CSV adapter
- In the Paste CSV here, including the header section paste the following:;
- None CSV Format
- Hit Submit
- Notice the following issue:

![image](https://cloud.githubusercontent.com/assets/20545238/19241874/9fc6c6fa-8ede-11e6-9e9d-a3aeb1b4dca2.png)

![image](https://cloud.githubusercontent.com/assets/20545238/19241966/0d29416e-8edf-11e6-9bcf-6e8a9293be25.png)

````
Traceback (most recent call last):
  File "/usr/share/edge/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/edge/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/lib/edge/python/adapters/csvind/views.py", line 78, in upload
    return do_upload(request)
  File "/var/lib/edge/python/adapters/csvind/views.py", line 56, in do_upload
    packagefd = package_from_csv(csvstream)
  File "/var/lib/edge/python/adapters/csvind/xforms_29.py", line 116, in package_from_csv
    params, csvhead, csvfd = start_csv(fd)
  File "/var/lib/edge/python/adapters/csvind/xforms_29.py", line 106, in start_csv
    data = next(csvstream)
StopIteration
```

**Comment by guitarmanvt** [comment]
I wouldn't classify this as a bug, because non-CSV data is really bad user input. Rather, this falls under "input validation" and probably could provide a helpful message so the user knows what to do next.
