### ISSUE TITLE
Unable to install this via Soltra Downloads within Edge 2.9-rc2(a)

### ISSUE THREAD

**Issue by guitarmanvt** [soltra-adapters/adapter-csvind#3]
I'm not sure whether this is an issue with core Edge or with the adapter. Dumping it here for the moment.

Steps to reproduce:
1. In Edge, Admin > Adapters.
2. Enter your username/password and Connect to Soltra Downloads.
3. Click the icon to Download "CSV Indicators Adapter 0.3.5".

Expected behavior: The download happens and Edge prompts to install the adapter.

Actual behavior: The download modal stays up and doesn't go away until you click off it. Also, it creates a Crash Log entry.

Crash log entry:
```
App: /adapters/ajax/download/
Message: u'CSV Indicators Adapter 0_3_5'
Traceback (most recent call last):
  File "/usr/share/edge/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/edge/users/decorators.py", line 50, in wrapper
    response = func(request, d)
  File "/usr/share/edge/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/share/edge/users/decorators.py", line 19, in wrapper
    return function(*args, **keyArgs)
  File "/usr/share/edge/adaptercore/download_views.py", line 134, in ajax_download_adapter
    download = scraper.download_tarball(key, save_local=False)
  File "/usr/share/edge/adaptercore/scraper.py", line 227, in download_tarball
    download = self.inventory.adapter_info[key]['download']
  File "/usr/share/edge/venv/lib/python2.7/site-packages/mongoengine/base/datastructures.py", line 25, in __getitem__
    value = super(BaseDict, self).__getitem__(*args, **kwargs)
KeyError: u'CSV Indicators Adapter 0_3_5'
```

**Comment by guitarmanvt** [comment]
See also: https://github.com/Soltra/rest-api-adapter/issues/26

**Comment by guitarmanvt** [comment]
Still affects 0.3.6

**Comment by guitarmanvt** [comment]
This is not a bug with this Adapter. It is a bug in Edge core. Moved to here: https://github.com/Soltra/repository/issues/1053

**Comment by guitarmanvt** [comment]
I was able to download this adapter from Soltra Downloads within the timeout period.
