### ISSUE TITLE
Cannot upload a CSV file due to namespace_alias not set

### ISSUE THREAD

**Issue by guitarmanvt** [soltra-adapters/adapter-csvind#4]
Steps to reproduce:
1. Navigate to Uploads in Edge.
2. Select the file type `urn:csvind.soltra.com:csv:0.1.0`
3. Upload the attached sample file. (It's a CSV, but I had to name it ".txt" to make GitHub attach it to this issue.) Here's the file: [test-csv-indicators.csv.txt](https://github.com/soltra-adapters/adapter-csvind/files/522160/test-csv-indicators.csv.txt)

Expected behavior: File is uploaded without errors.

Actual behaivor: The following error occurs: `Unhandled exception: namespace_alias must be set`

Crashlog:
```
App: process_upload
Message: upload_id 57fcfbed421aa922085f20d8 namespace_alias must be set
Traceback (most recent call last):
  File "uploads/jobs.py", line 93, in process_upload
    on_upload(upload)
  File "/var/lib/edge/python/adapters/csvind/xforms_23.py", line 248, in csvind_inbox
    package_fd = package_from_csv(upload_fd)
  File "/var/lib/edge/python/adapters/csvind/xforms_23.py", line 120, in package_from_csv
    raise ValueError("namespace_alias must be set")
ValueError: namespace_alias must be set
```

**Comment by guitarmanvt** [comment]
The test file still fails with the same error on 0.3.6.

**Comment by guitarmanvt** [comment]
When I use a CSV file that contains metadata headers, it works fine. For example, this file uploads fine: 
[test-csv-indicators-with-metadata-threatbump.csv.txt](https://github.com/soltra-adapters/adapter-csvind/files/522657/test-csv-indicators-with-metadata-threatbump.csv.txt)

Do we document the required headers anywhere? IF so, this is a "wontfix".

**Comment by guitarmanvt** [comment]
Specifically, the metadata headers it needs are like this example:
```
namespace_alias=tb
namespace_data=http://threatbump.com
head_title=ThreatBump Latest
head_description=This is the latest data from ThreatBump
```

**Comment by guitarmanvt** [comment]
Those fields are present in the UI as form fields.
