### ISSUE TITLE
Getting an error with CSV indicators - CSV v0.3-2.6

### ISSUE THREAD

**Issue by adamharaz** [soltra-adapters/adapter-csvind#7]
**Steps to reproduce:**
- Log into Edge 2.9 rc4 as an admin
- Download and upload CSV adapter recent v0.3-2.6
- Navigate to CSV Indicators
- Fill out the necessary fields as follow and click `submit`. 

![image](https://cloud.githubusercontent.com/assets/20545238/19613139/a67b70b2-97b8-11e6-9a04-0a72eeb86eac.png)

![image](https://cloud.githubusercontent.com/assets/20545238/19613142/b258d596-97b8-11e6-98ad-6fbb97fba5fd.png)

![image](https://cloud.githubusercontent.com/assets/20545238/19613132/9a1327de-97b8-11e6-9834-59db8393c9b8.png)

`````
Traceback (most recent call last):
  File "/usr/share/edge/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/edge/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/lib/edge/adapters/adapters/csvind/views.py", line 78, in upload
    return do_upload(request)
  File "/var/lib/edge/adapters/adapters/csvind/views.py", line 56, in do_upload
    packagefd = package_from_csv(csvstream)
  File "/var/lib/edge/adapters/adapters/csvind/xforms_29.py", line 116, in package_from_csv
    params, csvhead, csvfd = start_csv(fd)
  File "/var/lib/edge/adapters/adapters/csvind/xforms_29.py", line 106, in start_csv
    data = next(csvstream)
StopIteration
````

**Comment by benjamin9999** [comment]
using v0.3.6 on Edge 2.9
